name: Feature request
description: Propose an enhancement to Gatewarden
title: "feature: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion.
        Please do not include license keys or other secrets.
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: What would you like Gatewarden to do?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Any alternative approaches you considered.
    validations:
      required: false
